formatting workflows upload patches

diff --git a/.github/workflows/autoformat.yml b/.github/workflows/autoformat.yml
--- a/.github/workflows/autoformat.yml
+++ b/.github/workflows/autoformat.yml
@@ -30,4 +30,24 @@ jobs:
             | grep -vE 'out/|vcpkg_installed/|vcpkg/'
             )
           
-          clang-format -i --dry-run -Werror $FILES main.cpp StaticHTTPPackets.cpp StaticWSPackets.cpp
+          clang-format -i $FILES main.cpp StaticHTTPPackets.cpp StaticWSPackets.cpp
+
+      - name: Create diff
+        run: |
+          if ! git diff --quiet; then
+            git diff > clang-format.patch
+            echo "Patch created, apply the patch from the action artifact to fix"
+          else
+            echo "No changes required"
+          fi
+
+      - name: Upload patch if exists
+        uses: actions/upload-artifact@v4
+        if: ${{hashFiles('autoformat.patch') != ''}}
+        with:
+          path: clang-format.patch
+
+      - name: Fail if patch exists
+        if: ${{hashFiles('autoformat.patch') != ''}}
+        run: |
+          exit 1
diff --git a/.github/workflows/style.yml b/.github/workflows/style.yml
--- a/.github/workflows/style.yml
+++ b/.github/workflows/style.yml
@@ -56,4 +56,25 @@ jobs:
           | grep -vE 'out/|vcpkg_installed/|vcpkg/'
           )
           
-          clang-tidy $FILES main.cpp StaticHTTPPackets.cpp StaticWSPackets.cpp -p out/build/x64-debug-linux
+          clang-tidy $FILES main.cpp StaticHTTPPackets.cpp StaticWSPackets.cpp -fix -p out/build/x64-debug-linux
+
+      - name: Create diff
+        run: |
+          if ! git diff --quiet; then
+            git diff > clang-tidy.patch
+            echo "Patch created, apply the patch from the action artifact to fix"
+            echo "Note that manual changes may be required for things that clang-tidy is unable to automatically fix"
+          else
+            echo "No changes required"
+          fi
+
+      - name: Upload patch if exists
+        uses: actions/upload-artifact@v4
+        if: ${{hashFiles('autoformat.patch') != ''}}
+        with:
+          path: clang-tidy.patch
+
+      - name: Fail if patch exists
+        if: ${{hashFiles('autoformat.patch') != ''}}
+        run: |
+          exit 1
